### ISSUE TITLE
Newer build?

### ISSUE THREAD

**Issue by gerroon** [lubomyr/vice-2.4#3]
Hi

I tried building this but I could not, it is beyond me at this point.

I am wondering if the dev would consider releasing a more recent version?  

According to this page the last build is a year old.

http://anddev.at.ua/load/emulators/vicec64_sdl/2-1-0-26

thanks

**Comment by lubomyr** [comment]
updated
http://anddev.at.ua/load/emulators/vicec64_sdl/2-1-0-26

2016-08-21 4:40 GMT+03:00 gerroon notifications@github.com:

**Comment by gerroon** [comment]
Thanks, I appreciate that you released a newer version.
