### ISSUE TITLE
2.4.0.5 screen cuts off

### ISSUE THREAD

**Issue by gerroon** [lubomyr/vice-2.4#7]
Hi
I installed that version however something is wrong with the screen res. I can only see the screen up until "...dore 6". It cuts off where "6 and 9 of 389" lines up vertically. And the horizantally it cuts off somewhere middle I think.

I am testing it with my Samsung Note 8 which has 1200x800 res

thanks

**Comment by lubomyr** [comment]
Try to turn off "Tv border" option in startup SDL menu, video settings.
Also you can try turn on 4:3 aspect ratio option.

2016-08-21 19:45 GMT+03:00 gerroon notifications@github.com:

**Comment by gerroon** [comment]
Nevermind, I uninstalled and reinstalled. The issue is resolved.
